// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl7AuVsky9UtBkTc8wTQIq84WroAJdLlc',
    appId: '1:73809517559:web:c88b690f7d6a60366dacf2',
    messagingSenderId: '73809517559',
    projectId: 'fir-tutorial-b3a3c',
    authDomain: 'fir-tutorial-b3a3c.firebaseapp.com',
    storageBucket: 'fir-tutorial-b3a3c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDm0wHK97yhVwL7zh8hl6w_m_Mo_Uvr5s',
    appId: '1:73809517559:android:140f9e09721d9fd46dacf2',
    messagingSenderId: '73809517559',
    projectId: 'fir-tutorial-b3a3c',
    storageBucket: 'fir-tutorial-b3a3c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl7AuVsky9UtBkTc8wTQIq84WroAJdLlc',
    appId: '1:73809517559:web:5aedc20ce3702f096dacf2',
    messagingSenderId: '73809517559',
    projectId: 'fir-tutorial-b3a3c',
    authDomain: 'fir-tutorial-b3a3c.firebaseapp.com',
    storageBucket: 'fir-tutorial-b3a3c.firebasestorage.app',
  );
}
